// <auto-generated />
using System;
using CarsWebsite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace cars_website_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CarsWebsite.Advert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvertType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Adverts");
                });

            modelBuilder.Entity("CarsWebsite.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarsWebsite.Advert", b =>
                {
                    b.HasOne("CarsWebsite.User", "createdBy")
                        .WithMany("Adverts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CarsWebsite.PartDetails", "PartDetails", b1 =>
                        {
                            b1.Property<int>("AdvertId")
                                .HasColumnType("int");

                            b1.Property<string>("Category")
                                .HasColumnType("longtext");

                            b1.Property<string>("Condition")
                                .HasColumnType("longtext");

                            b1.Property<string>("PartNumber")
                                .HasColumnType("longtext");

                            b1.HasKey("AdvertId");

                            b1.ToTable("Adverts");

                            b1.WithOwner()
                                .HasForeignKey("AdvertId");
                        });

                    b.OwnsOne("CarsWebsite.VehicleDetails", "VehicleDetails", b1 =>
                        {
                            b1.Property<int>("AdvertId")
                                .HasColumnType("int");

                            b1.Property<string>("Brand")
                                .HasColumnType("longtext");

                            b1.Property<string>("Color")
                                .HasColumnType("longtext");

                            b1.Property<string>("Condition")
                                .HasColumnType("longtext");

                            b1.Property<int?>("EngineSize")
                                .HasColumnType("int");

                            b1.Property<string>("FuelType")
                                .HasColumnType("longtext");

                            b1.Property<int?>("HorsePower")
                                .HasColumnType("int");

                            b1.Property<int?>("Mileage")
                                .HasColumnType("int");

                            b1.Property<string>("Model")
                                .HasColumnType("longtext");

                            b1.Property<string>("Transmission")
                                .HasColumnType("longtext");

                            b1.Property<string>("VehicleType")
                                .HasColumnType("longtext");

                            b1.Property<int?>("Year")
                                .HasColumnType("int");

                            b1.HasKey("AdvertId");

                            b1.ToTable("Adverts");

                            b1.WithOwner()
                                .HasForeignKey("AdvertId");
                        });

                    b.Navigation("PartDetails");

                    b.Navigation("VehicleDetails");

                    b.Navigation("createdBy");
                });

            modelBuilder.Entity("CarsWebsite.User", b =>
                {
                    b.Navigation("Adverts");
                });
#pragma warning restore 612, 618
        }
    }
}
